import { Task, TaskCategory, CategoryStyle } from './types'

export const CATEGORY_STYLES: Record<TaskCategory, CategoryStyle> = {
  Medical: {
    bg: 'bg-medical/10',
    text: 'text-medical',
    icon: 'medical_services',
    border: 'border-medical/30',
    progress: 'bg-medical',
  },
  Finance: {
    bg: 'bg-green-500/10',
    text: 'text-green-400',
    icon: 'attach_money',
    border: 'border-green-500/30',
    progress: 'bg-green-500',
  },
  Gear: {
    bg: 'bg-purple-500/10',
    text: 'text-purple-400',
    icon: 'shopping_bag',
    border: 'border-purple-500/30',
    progress: 'bg-purple-500',
  },
  Home: {
    bg: 'bg-teal-500/10',
    text: 'text-teal-400',
    icon: 'home',
    border: 'border-teal-500/30',
    progress: 'bg-teal-500',
  },
  Childcare: {
    bg: 'bg-orange-500/10',
    text: 'text-orange-400',
    icon: 'child_care',
    border: 'border-orange-500/30',
    progress: 'bg-orange-500',
  },
  Admin: {
    bg: 'bg-gray-500/10',
    text: 'text-gray-400',
    icon: 'description',
    border: 'border-gray-500/30',
    progress: 'bg-gray-500',
  },
  Preparation: {
    bg: 'bg-pink-500/10',
    text: 'text-pink-400',
    icon: 'checklist',
    border: 'border-pink-500/30',
    progress: 'bg-pink-500',
  },
}

export const DEFAULT_TASKS: Task[] = [
  // ============ TRIMESTER 1 (Weeks 1-12) ============
  {
    id: 't1-1',
    title: 'Start prenatal vitamins',
    description: 'Begin taking folic acid and prenatal vitamins daily.',
    category: 'Medical',
    trimester: 1,
    weekDue: 4,
    completed: false,
    userAdded: false,
  },
  {
    id: 't1-2',
    title: 'Schedule first prenatal appointment',
    description: 'Book appointment with OB/GYN or midwife for 8-week visit.',
    category: 'Medical',
    trimester: 1,
    weekDue: 6,
    completed: false,
    userAdded: false,
  },
  {
    id: 't1-3',
    title: 'Review health insurance coverage',
    description: 'Understand deductibles, OOP max, and maternity coverage details.',
    category: 'Finance',
    trimester: 1,
    weekDue: 8,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: 'Before major medical bills',
    consequence: 'Unexpected $10K+ bills if coverage gaps exist',
  },
  {
    id: 't1-4',
    title: 'Start emergency fund',
    description: 'Begin saving for baby-related expenses. Target: 3-6 months expenses.',
    category: 'Finance',
    trimester: 1,
    weekDue: 8,
    completed: false,
    userAdded: false,
  },
  {
    id: 't1-5',
    title: 'Research hospital vs birthing center',
    description: 'Compare options, costs, and policies for delivery location.',
    category: 'Medical',
    trimester: 1,
    weekDue: 10,
    completed: false,
    userAdded: false,
  },
  {
    id: 't1-6',
    title: 'Review life insurance needs',
    description: 'Consider term life policies for both parents.',
    category: 'Finance',
    trimester: 1,
    weekDue: 10,
    completed: false,
    userAdded: false,
  },
  {
    id: 't1-7',
    title: 'Research parental leave policies',
    description: "Understand your employer's leave policy and FMLA rights.",
    category: 'Admin',
    trimester: 1,
    weekDue: 12,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: 'Before requesting leave',
    consequence: 'May lose paid leave benefits if not properly requested',
  },

  // ============ TRIMESTER 2 (Weeks 13-26) ============
  {
    id: 't2-1',
    title: 'Research daycare options',
    description: 'Get on waitlists early - some have 12+ month waits.',
    category: 'Childcare',
    trimester: 2,
    weekDue: 16,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: 'ASAP - waitlists are long',
    consequence: 'No childcare spot when you return to work',
  },
  {
    id: 't2-2',
    title: 'Start baby registry',
    description: 'Create registry and research essential gear.',
    category: 'Gear',
    trimester: 2,
    weekDue: 18,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-3',
    title: 'Research life insurance',
    description: 'Comparison shop term life policies for both parents.',
    category: 'Finance',
    trimester: 2,
    weekDue: 18,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-4',
    title: 'Buy crib & mattress',
    description: 'Estimated cost: $300-600. Check CPSC safety standards.',
    category: 'Gear',
    trimester: 2,
    weekDue: 20,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-5',
    title: 'Anatomy scan (20-week ultrasound)',
    description: 'Major prenatal screening appointment.',
    category: 'Medical',
    trimester: 2,
    weekDue: 20,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-6',
    title: 'Pre-register at hospital',
    description: 'Complete paperwork before delivery day chaos.',
    category: 'Medical',
    trimester: 2,
    weekDue: 20,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-7',
    title: 'Paint nursery',
    description: 'Select low-VOC paint. Complete before 3rd trimester.',
    category: 'Home',
    trimester: 2,
    weekDue: 22,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-8',
    title: 'Sign up for childbirth class',
    description: 'Most classes fill up - book early.',
    category: 'Preparation',
    trimester: 2,
    weekDue: 20,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-9',
    title: 'Interview pediatricians',
    description: 'Meet with 2-3 pediatricians before choosing.',
    category: 'Medical',
    trimester: 2,
    weekDue: 24,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-10',
    title: 'Update will and beneficiaries',
    description: 'Legal documents to update for new family member.',
    category: 'Finance',
    trimester: 2,
    weekDue: 22,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-11',
    title: 'Purchase car seat',
    description: 'Required for hospital discharge. Budget: $200-400.',
    category: 'Gear',
    trimester: 2,
    weekDue: 24,
    completed: false,
    userAdded: false,
  },
  {
    id: 't2-12',
    title: 'Schedule hospital tour',
    description: 'Know where to go and what to expect on delivery day.',
    category: 'Preparation',
    trimester: 2,
    weekDue: 24,
    completed: false,
    userAdded: false,
  },

  // ============ TRIMESTER 3 (Weeks 27-40) ============
  {
    id: 't3-1',
    title: 'Glucose screening test',
    description: 'Standard gestational diabetes screening.',
    category: 'Medical',
    trimester: 3,
    weekDue: 28,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-2',
    title: 'Submit FMLA paperwork',
    description: 'File required forms with HR.',
    category: 'Admin',
    trimester: 3,
    weekDue: 30,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: '30 days before leave starts',
    consequence: 'Leave may be denied or unpaid if filed late',
  },
  {
    id: 't3-3',
    title: 'Set up nursery',
    description: 'Assemble furniture, organize supplies.',
    category: 'Home',
    trimester: 3,
    weekDue: 32,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-4',
    title: 'Wash baby clothes and bedding',
    description: 'Use fragrance-free detergent.',
    category: 'Home',
    trimester: 3,
    weekDue: 34,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-5',
    title: 'Stock up on diapers and wipes',
    description: "Newborn and Size 1 diapers. Don't overbuy one size.",
    category: 'Gear',
    trimester: 3,
    weekDue: 34,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-6',
    title: 'Pack hospital bag',
    description: 'Essentials for mom, dad, and baby.',
    category: 'Preparation',
    trimester: 3,
    weekDue: 35,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-7',
    title: 'Install car seat',
    description: 'Get it inspected at local fire station or hospital.',
    category: 'Gear',
    trimester: 3,
    weekDue: 36,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: 'Before labor begins',
    consequence: 'Hospital will not discharge baby without installed car seat',
  },
  {
    id: 't3-8',
    title: 'Group B strep test',
    description: 'Standard screening at 36 weeks.',
    category: 'Medical',
    trimester: 3,
    weekDue: 36,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-9',
    title: 'Prepare freezer meals',
    description: 'Stock up on easy meals for post-baby chaos.',
    category: 'Preparation',
    trimester: 3,
    weekDue: 36,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-10',
    title: 'Finalize baby name',
    description: 'Final decision time!',
    category: 'Preparation',
    trimester: 3,
    weekDue: 37,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-11',
    title: 'Review insurance for adding baby',
    description: 'Know the 30-day window to add baby after birth.',
    category: 'Finance',
    trimester: 3,
    weekDue: 34,
    completed: false,
    userAdded: false,
    isHighStakes: true,
    deadline: 'Birth + 30 days',
    consequence: '$0 insurance coverage for baby if window missed',
  },
  {
    id: 't3-12',
    title: 'Create emergency contact list',
    description: 'Phone numbers for pediatrician, hospital, family.',
    category: 'Preparation',
    trimester: 3,
    weekDue: 38,
    completed: false,
    userAdded: false,
  },
  {
    id: 't3-13',
    title: 'Confirm pediatrician for newborn visit',
    description: 'Schedule appointment within 3-5 days of birth.',
    category: 'Medical',
    trimester: 3,
    weekDue: 38,
    completed: false,
    userAdded: false,
  },
]
